/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GalleryUploadId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryUpload = IDL.Record({
  'id' : GalleryUploadId,
  'uploaderPrincipal' : IDL.Principal,
  'approved' : IDL.Bool,
  'caption' : IDL.Opt(IDL.Text),
  'photo' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const AdminConfessionView = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'submittedBy' : IDL.Opt(IDL.Text),
  'approved' : IDL.Bool,
});
export const ApplicationId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'approved' : IDL.Nat,
  'rejected' : IDL.Nat,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const GuestQuizResult = IDL.Record({
  'applicationId' : IDL.Nat,
  'takenAt' : IDL.Int,
  'resultType' : IDL.Text,
});
export const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const QuizResult = IDL.Record({
  'description' : IDL.Text,
  'resultType' : IDL.Text,
});
export const UserId = IDL.Nat;
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'emailOrPhone' : IDL.Text,
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'profilePhoto' : IDL.Opt(IDL.Text),
  'instagramHandle' : IDL.Opt(IDL.Text),
  'linkedApplicationId' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
  'profileCompleted' : IDL.Opt(IDL.Bool),
});
export const ApplicationView = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'plusOne' : IDL.Opt(IDL.Bool),
  'applicantPrincipal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'qrToken' : IDL.Opt(IDL.Text),
  'inviteCode' : IDL.Text,
  'phone' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const ConfessionView = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'approved' : IDL.Bool,
});
export const UserLoginInput = IDL.Record({
  'emailOrPhone' : IDL.Text,
  'password' : IDL.Text,
});
export const UserSessionResult = IDL.Record({
  'token' : IDL.Text,
  'user' : UserProfile,
});
export const UserSignUpInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'emailOrPhone' : IDL.Text,
  'city' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(IDL.Text),
  'instagramHandle' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
});
export const ApplicationInput = IDL.Record({
  'plusOne' : IDL.Opt(IDL.Bool),
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'email' : IDL.Text,
  'inviteCode' : IDL.Text,
  'phone' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'profilePhoto' : IDL.Opt(IDL.Text),
  'instagramHandle' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addInviteCode' : IDL.Func([IDL.Text], [], []),
  'adminApproveConfession' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveGalleryPhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteConfession' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllGalleryPhotos' : IDL.Func(
      [],
      [IDL.Vec(GalleryUpload)],
      ['query'],
    ),
  'adminListConfessions' : IDL.Func(
      [],
      [IDL.Vec(AdminConfessionView)],
      ['query'],
    ),
  'adminRejectGalleryPhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveApplication' : IDL.Func([ApplicationId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'broadcastToApprovedGuests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getApplicationStatus' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(IDL.Tuple(ApplicationStatus, IDL.Opt(IDL.Text)))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyQuizResult' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(GuestQuizResult)],
      ['query'],
    ),
  'getPublicGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryUpload)], ['query']),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getQuizResultTypes' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getRegisteredUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserApplicationStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ApplicationView, 'err' : IDL.Text })],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'linkApplicationToUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listApplications' : IDL.Func([], [IDL.Vec(ApplicationView)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listConfessions' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(ConfessionView)],
      ['query'],
    ),
  'listInviteCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'login' : IDL.Func(
      [UserLoginInput],
      [IDL.Variant({ 'ok' : UserSessionResult, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'rejectApplication' : IDL.Func([ApplicationId], [], []),
  'removeAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'resendApprovalEmail' : IDL.Func(
      [ApplicationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'signUp' : IDL.Func(
      [UserSignUpInput],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
  'submitConfession' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'submitQuizResult' : IDL.Func([ApplicationId, IDL.Text], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, UpdateProfileInput],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'uploadGalleryPhoto' : IDL.Func(
      [ExternalBlob, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifySession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GalleryUploadId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryUpload = IDL.Record({
    'id' : GalleryUploadId,
    'uploaderPrincipal' : IDL.Principal,
    'approved' : IDL.Bool,
    'caption' : IDL.Opt(IDL.Text),
    'photo' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const AdminConfessionView = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'submittedBy' : IDL.Opt(IDL.Text),
    'approved' : IDL.Bool,
  });
  const ApplicationId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'approved' : IDL.Nat,
    'rejected' : IDL.Nat,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const GuestQuizResult = IDL.Record({
    'applicationId' : IDL.Nat,
    'takenAt' : IDL.Int,
    'resultType' : IDL.Text,
  });
  const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const QuizResult = IDL.Record({
    'description' : IDL.Text,
    'resultType' : IDL.Text,
  });
  const UserId = IDL.Nat;
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'emailOrPhone' : IDL.Text,
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'profilePhoto' : IDL.Opt(IDL.Text),
    'instagramHandle' : IDL.Opt(IDL.Text),
    'linkedApplicationId' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
    'profileCompleted' : IDL.Opt(IDL.Bool),
  });
  const ApplicationView = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'plusOne' : IDL.Opt(IDL.Bool),
    'applicantPrincipal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'qrToken' : IDL.Opt(IDL.Text),
    'inviteCode' : IDL.Text,
    'phone' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const ConfessionView = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'approved' : IDL.Bool,
  });
  const UserLoginInput = IDL.Record({
    'emailOrPhone' : IDL.Text,
    'password' : IDL.Text,
  });
  const UserSessionResult = IDL.Record({
    'token' : IDL.Text,
    'user' : UserProfile,
  });
  const UserSignUpInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'emailOrPhone' : IDL.Text,
    'city' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(IDL.Text),
    'instagramHandle' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
  });
  const ApplicationInput = IDL.Record({
    'plusOne' : IDL.Opt(IDL.Bool),
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'email' : IDL.Text,
    'inviteCode' : IDL.Text,
    'phone' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'profilePhoto' : IDL.Opt(IDL.Text),
    'instagramHandle' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addInviteCode' : IDL.Func([IDL.Text], [], []),
    'adminApproveConfession' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveGalleryPhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteConfession' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllGalleryPhotos' : IDL.Func(
        [],
        [IDL.Vec(GalleryUpload)],
        ['query'],
      ),
    'adminListConfessions' : IDL.Func(
        [],
        [IDL.Vec(AdminConfessionView)],
        ['query'],
      ),
    'adminRejectGalleryPhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveApplication' : IDL.Func([ApplicationId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'broadcastToApprovedGuests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getApplicationStatus' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(IDL.Tuple(ApplicationStatus, IDL.Opt(IDL.Text)))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyQuizResult' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(GuestQuizResult)],
        ['query'],
      ),
    'getPublicGalleryPhotos' : IDL.Func(
        [],
        [IDL.Vec(GalleryUpload)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getQuizResultTypes' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getRegisteredUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserApplicationStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ApplicationView, 'err' : IDL.Text })],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'linkApplicationToUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listApplications' : IDL.Func([], [IDL.Vec(ApplicationView)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listConfessions' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(ConfessionView)],
        ['query'],
      ),
    'listInviteCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'login' : IDL.Func(
        [UserLoginInput],
        [IDL.Variant({ 'ok' : UserSessionResult, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'rejectApplication' : IDL.Func([ApplicationId], [], []),
    'removeAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'resendApprovalEmail' : IDL.Func(
        [ApplicationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'signUp' : IDL.Func(
        [UserSignUpInput],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
    'submitConfession' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'submitQuizResult' : IDL.Func([ApplicationId, IDL.Text], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, UpdateProfileInput],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'uploadGalleryPhoto' : IDL.Func(
        [ExternalBlob, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifySession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };