/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'total' : bigint,
  'pending' : bigint,
  'approved' : bigint,
  'rejected' : bigint,
}
export type ApplicationId = bigint;
export interface ApplicationInput {
  'plusOne' : boolean,
  'name' : string,
  'instagramHandle' : string,
  'email' : string,
  'inviteCode' : string,
  'phone' : string,
  'photos' : Array<ExternalBlob>,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ApplicationView {
  'id' : bigint,
  'status' : ApplicationStatus,
  'plusOne' : boolean,
  'name' : string,
  'instagramHandle' : string,
  'submittedAt' : bigint,
  'email' : string,
  'qrToken' : [] | [string],
  'inviteCode' : string,
  'phone' : string,
  'photos' : Array<ExternalBlob>,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Confession {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
}
export type ExternalBlob = Uint8Array;
export interface GuestQuizResult {
  'applicationId' : bigint,
  'takenAt' : bigint,
  'resultType' : string,
}
export interface QuizOption { 'id' : bigint, 'text' : string }
export interface QuizQuestion {
  'id' : bigint,
  'text' : string,
  'options' : Array<QuizOption>,
}
export interface QuizResult { 'description' : string, 'resultType' : string }
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addInviteCode' : ActorMethod<[string], undefined>,
  'approveApplication' : ActorMethod<[ApplicationId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getApplicationStatus' : ActorMethod<
    [ApplicationId],
    [] | [[ApplicationStatus, [] | [string]]]
  >,
  'getApprovedPhotos' : ActorMethod<[], Array<ExternalBlob>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyQuizResult' : ActorMethod<[ApplicationId], [] | [GuestQuizResult]>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getQuizResultTypes' : ActorMethod<[], Array<QuizResult>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApplications' : ActorMethod<[], Array<ApplicationView>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listConfessions' : ActorMethod<[], Array<Confession>>,
  'listInviteCodes' : ActorMethod<[], Array<string>>,
  'rejectApplication' : ActorMethod<[ApplicationId], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitApplication' : ActorMethod<[ApplicationInput], ApplicationId>,
  'submitConfession' : ActorMethod<[string], bigint>,
  'submitQuizResult' : ActorMethod<[ApplicationId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];