/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfessionView {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'submittedBy' : [] | [string],
  'approved' : boolean,
}
export interface AdminStats {
  'total' : bigint,
  'pending' : bigint,
  'approved' : bigint,
  'rejected' : bigint,
}
export type ApplicationId = bigint;
export interface ApplicationInput {
  'plusOne' : [] | [boolean],
  'name' : string,
  'instagramHandle' : string,
  'email' : string,
  'inviteCode' : string,
  'phone' : string,
  'photos' : Array<ExternalBlob>,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ApplicationView {
  'id' : bigint,
  'status' : ApplicationStatus,
  'plusOne' : [] | [boolean],
  'applicantPrincipal' : [] | [Principal],
  'name' : string,
  'instagramHandle' : string,
  'submittedAt' : bigint,
  'email' : string,
  'qrToken' : [] | [string],
  'inviteCode' : string,
  'phone' : string,
  'photos' : Array<ExternalBlob>,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ConfessionView {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'approved' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface GalleryUpload {
  'id' : GalleryUploadId,
  'uploaderPrincipal' : Principal,
  'approved' : boolean,
  'caption' : [] | [string],
  'photo' : ExternalBlob,
  'uploadedAt' : bigint,
}
export type GalleryUploadId = string;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface GuestQuizResult {
  'applicationId' : bigint,
  'takenAt' : bigint,
  'resultType' : string,
}
export interface QuizOption { 'id' : bigint, 'text' : string }
export interface QuizQuestion {
  'id' : bigint,
  'text' : string,
  'options' : Array<QuizOption>,
}
export interface QuizResult { 'description' : string, 'resultType' : string }
export interface UpdateProfileInput {
  'bio' : [] | [string],
  'city' : [] | [string],
  'name' : [] | [string],
  'profilePhoto' : [] | [string],
  'instagramHandle' : [] | [string],
  'gender' : [] | [Gender],
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserId = bigint;
export interface UserLoginInput { 'emailOrPhone' : string, 'password' : string }
export interface UserProfile {
  'id' : UserId,
  'bio' : [] | [string],
  'emailOrPhone' : string,
  'city' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'profilePhoto' : [] | [string],
  'instagramHandle' : [] | [string],
  'linkedApplicationId' : [] | [string],
  'gender' : [] | [Gender],
  'profileCompleted' : [] | [boolean],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSessionResult { 'token' : string, 'user' : UserProfile }
export interface UserSignUpInput {
  'bio' : [] | [string],
  'emailOrPhone' : string,
  'city' : [] | [string],
  'password' : string,
  'name' : string,
  'profilePhoto' : [] | [string],
  'instagramHandle' : [] | [string],
  'gender' : [] | [Gender],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAdmin' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'addInviteCode' : ActorMethod<[string], undefined>,
  'adminApproveConfession' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveGalleryPhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteConfession' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllGalleryPhotos' : ActorMethod<[], Array<GalleryUpload>>,
  'adminListConfessions' : ActorMethod<[], Array<AdminConfessionView>>,
  'adminRejectGalleryPhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveApplication' : ActorMethod<[ApplicationId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'broadcastToApprovedGuests' : ActorMethod<
    [string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getApplicationStatus' : ActorMethod<
    [ApplicationId],
    [] | [[ApplicationStatus, [] | [string]]]
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyQuizResult' : ActorMethod<[ApplicationId], [] | [GuestQuizResult]>,
  'getPublicGalleryPhotos' : ActorMethod<[], Array<GalleryUpload>>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getQuizResultTypes' : ActorMethod<[], Array<QuizResult>>,
  'getRegisteredUsers' : ActorMethod<[], Array<UserProfile>>,
  'getTotalUserCount' : ActorMethod<[], bigint>,
  'getUserApplicationStatus' : ActorMethod<
    [string],
    { 'ok' : ApplicationView } |
      { 'err' : string }
  >,
  'getUserProfile' : ActorMethod<
    [string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'linkApplicationToUser' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'listApplications' : ActorMethod<[], Array<ApplicationView>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listConfessions' : ActorMethod<[[] | [string]], Array<ConfessionView>>,
  'listInviteCodes' : ActorMethod<[], Array<string>>,
  'login' : ActorMethod<
    [UserLoginInput],
    { 'ok' : UserSessionResult } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'rejectApplication' : ActorMethod<[ApplicationId], undefined>,
  'removeAdmin' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'resendApprovalEmail' : ActorMethod<
    [ApplicationId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'signUp' : ActorMethod<
    [UserSignUpInput],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'submitApplication' : ActorMethod<[ApplicationInput], ApplicationId>,
  'submitConfession' : ActorMethod<[string, [] | [string]], bigint>,
  'submitQuizResult' : ActorMethod<[ApplicationId, string], undefined>,
  'updateUserProfile' : ActorMethod<
    [string, UpdateProfileInput],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'uploadGalleryPhoto' : ActorMethod<
    [ExternalBlob, [] | [string], [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifySession' : ActorMethod<
    [string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];