/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ApplicationId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'approved' : IDL.Nat,
  'rejected' : IDL.Nat,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GuestQuizResult = IDL.Record({
  'applicationId' : IDL.Nat,
  'takenAt' : IDL.Int,
  'resultType' : IDL.Text,
});
export const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const QuizResult = IDL.Record({
  'description' : IDL.Text,
  'resultType' : IDL.Text,
});
export const ApplicationView = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'plusOne' : IDL.Opt(IDL.Bool),
  'applicationId' : IDL.Text,
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'qrToken' : IDL.Opt(IDL.Text),
  'inviteCode' : IDL.Text,
  'phone' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const Confession = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
});
export const ApplicationInput = IDL.Record({
  'plusOne' : IDL.Opt(IDL.Bool),
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'email' : IDL.Text,
  'inviteCode' : IDL.Text,
  'phone' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addInviteCode' : IDL.Func([IDL.Text], [], []),
  'approveApplication' : IDL.Func([ApplicationId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'broadcastToApprovedGuests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getApplicationStatus' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(IDL.Tuple(ApplicationStatus, IDL.Opt(IDL.Text)))],
      ['query'],
    ),
  'getApprovedPhotos' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyQuizResult' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(GuestQuizResult)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getQuizResultTypes' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listApplications' : IDL.Func([], [IDL.Vec(ApplicationView)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
  'listInviteCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'rejectApplication' : IDL.Func([ApplicationId], [], []),
  'removeAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'resendApprovalEmail' : IDL.Func(
      [ApplicationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
  'submitConfession' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'submitQuizResult' : IDL.Func([ApplicationId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ApplicationId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'approved' : IDL.Nat,
    'rejected' : IDL.Nat,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GuestQuizResult = IDL.Record({
    'applicationId' : IDL.Nat,
    'takenAt' : IDL.Int,
    'resultType' : IDL.Text,
  });
  const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const QuizResult = IDL.Record({
    'description' : IDL.Text,
    'resultType' : IDL.Text,
  });
  const ApplicationView = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'plusOne' : IDL.Opt(IDL.Bool),
    'applicationId' : IDL.Text,
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'qrToken' : IDL.Opt(IDL.Text),
    'inviteCode' : IDL.Text,
    'phone' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const Confession = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
  });
  const ApplicationInput = IDL.Record({
    'plusOne' : IDL.Opt(IDL.Bool),
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'email' : IDL.Text,
    'inviteCode' : IDL.Text,
    'phone' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addInviteCode' : IDL.Func([IDL.Text], [], []),
    'approveApplication' : IDL.Func([ApplicationId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'broadcastToApprovedGuests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getApplicationStatus' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(IDL.Tuple(ApplicationStatus, IDL.Opt(IDL.Text)))],
        ['query'],
      ),
    'getApprovedPhotos' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyQuizResult' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(GuestQuizResult)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getQuizResultTypes' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listApplications' : IDL.Func([], [IDL.Vec(ApplicationView)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listConfessions' : IDL.Func([], [IDL.Vec(Confession)], ['query']),
    'listInviteCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'rejectApplication' : IDL.Func([ApplicationId], [], []),
    'removeAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'resendApprovalEmail' : IDL.Func(
        [ApplicationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
    'submitConfession' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'submitQuizResult' : IDL.Func([ApplicationId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };